import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class AppData {
  public NO2_MIN = 11.7;
  public NO2_MAX = 40;
  public SO2 = 3.5;
  public PM2_5 = 1.34;
  public PM10_MIN = 42;
  public PM10_MAX = 60;
  public O3 = 40;
  public CO = 1.34;
  public AIR_QUALITY_MONETIZATION_MIN = 0.012;
  public AIR_QUALITY_MONETIZATION_MAX = 0.014;
  public CO2_SEQUESTRATION_MIN = 0.14;
  public CO2_SEQUESTRATION_MAX = 0.98;
  public CO2_SEQUESTRATION_MONETIZATION_MIN = 2;
  public CO2_SEQUESTRATION_MONETIZATION_MAX = 2.3;
  public NO3_REDUCTION_MIN = 30;
  public NO3_REDUCTION_MAX = 83;
  public TSS_REDUCTION_MIN = 33;
  public TSS_REDUCTION_MAX = 99;
  public P_REDUCTION_MIN = 15;
  public P_REDUCTION_MAX = 30;
  public WATER_RETENTION_MIN = 0;
  public WATER_RETENTION_MAX = 75;
  public WATER_RETENTION_MONETIZATION_MIN = 12.27;
  public WATER_RETENTION_MONETIZATION_MAX = 22.91;
  public TEMPERATURE_OUTDOOR_MIN = 1;
  public TEMPERATURE_OUTDOOR_MAX = 4.1;
  public TEMPERATURE_INDOOR = 4.8;
  public NOISE_REDUCTION_MIN = 5.5;
  public NOISE_REDUCTION_MAX = 9.8;
  public ENERGY_REDUCTION_MIN = 10;
  public ENERGY_REDUCTION_MAX = 60;
  public ENERGY_REDUCTION_MONETIZATION_MIN = 4;
  public ENERGY_REDUCTION_MONETIZATION_MAX = 9.4;
  public ENVIRONMENTAL_AVOIDED_COSTS_MIN = 14.28;
  public ENVIRONMENTAL_AVOIDED_COSTS_MAX = 25.21;
  public MEMBRANE_LONGEVITY_MONETIZATION = 133793;
  public PROPERTY_VALUE_MONETIZATION = 4.33;
  public BIOMASS_PRODUCTION_MONETIZATION = 2.12;
  public MAINTENANCE = 18.98;
  public INVESTMENT_MIN = 408;
  public INVESTMENT_MAX = 1091;
  public DISPOSAL = 239;
  public TOTAL_BENEFITS_MIN =
    this.AIR_QUALITY_MONETIZATION_MIN +
    this.CO2_SEQUESTRATION_MONETIZATION_MIN +
    this.WATER_RETENTION_MONETIZATION_MIN +
    this.ENERGY_REDUCTION_MONETIZATION_MIN +
    this.BIOMASS_PRODUCTION_MONETIZATION +
    this.PROPERTY_VALUE_MONETIZATION;
  public TOTAL_BENEFITS_MAX =
    this.AIR_QUALITY_MONETIZATION_MAX +
    this.CO2_SEQUESTRATION_MONETIZATION_MAX +
    this.WATER_RETENTION_MONETIZATION_MAX +
    this.ENERGY_REDUCTION_MONETIZATION_MAX +
    this.BIOMASS_PRODUCTION_MONETIZATION +
    this.PROPERTY_VALUE_MONETIZATION;
}
